# Generated by Django 3.0.3 on 2020-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length = 40)),
                ('card_number', models.CharField(max_length=20)),
                ('expDate', models.CharField(max_length=5)),
                ('cardType', models.CharField(max_length=15)),
                ('cvv', models.CharField(max_length=3)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zipCode', models.CharField(max_length=5)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('nickName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
