# Generated by Django 3.0.3 on 2020-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=40)),
                ('years', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=2)),
                ('comment', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
    ]
