# Generated by Django 3.0.3 on 2020-05-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
